import type { ProjectFile } from "@/lib/types";
// lz-string ships with @codesandbox/sandpack-react — already in node_modules
// eslint-disable-next-line @typescript-eslint/no-require-imports
const LZString = require("lz-string") as { compressToBase64: (s: string) => string };

type CSBFile = { content: string };

/**
 * Open the current project in CodeSandbox.
 *
 * Uses the hidden-form POST approach: browser submits a form to
 * codesandbox.io, which opens the sandbox in a new tab. This avoids the
 * CORS restriction on fetch() AND bypasses Cloudflare bot detection that
 * blocks server-to-server requests.
 *
 * Spec: https://codesandbox.io/docs/learn/browser-sandboxes/cli-api
 */
export function openInCodeSandbox(files: ProjectFile[]): void {
  const csFiles: Record<string, CSBFile> = {};

  for (const file of files) {
    // CodeSandbox vanilla template expects index.js, not app.js
    const filename = file.name === "app.js" ? "index.js" : file.name;
    csFiles[filename] = { content: file.content };
  }

  // Vanilla (Parcel) template needs an explicit package.json
  if (!csFiles["package.json"]) {
    csFiles["package.json"] = {
      content: JSON.stringify(
        {
          name: "forge-export",
          version: "1.0.0",
          description: "Generated by FORGE",
          main: "index.js",
          scripts: {
            start: "parcel index.html --open",
            build: "parcel build index.html",
          },
          devDependencies: { "parcel-bundler": "^1.6.1" },
        },
        null,
        2
      ),
    };
  }

  const parameters = LZString.compressToBase64(JSON.stringify({ files: csFiles }));

  const form = document.createElement("form");
  form.method = "POST";
  form.action = "https://codesandbox.io/api/v1/sandboxes/define";
  form.target = "_blank";
  form.style.display = "none";

  const input = document.createElement("input");
  input.type = "hidden";
  input.name = "parameters";
  input.value = parameters;

  form.appendChild(input);
  document.body.appendChild(form);
  form.submit();
  document.body.removeChild(form);
}
