import { Hono } from "hono";
import type { ProjectFile } from "@/lib/types";

export const codesandboxRoutes = new Hono();

type DefineRequest = {
  files: ProjectFile[];
};

type CodeSandboxDefineResponse = {
  sandbox_id?: string;
};

/**
 * Server-side proxy for the CodeSandbox Define API.
 *
 * Browser-side POST is blocked by CORS, so the client posts to this route and
 * we forward server-to-server. CodeSandbox expects a flat `files` map keyed by
 * path. Our `app.js` maps to `index.js` because the vanilla template entry is
 * always /index.js (same convention as Sandpack vanilla).
 */
codesandboxRoutes.post("/", async (c) => {
  let body: DefineRequest;
  try {
    body = await c.req.json<DefineRequest>();
  } catch {
    return c.json({ error: "Invalid JSON" }, 400);
  }

  if (!Array.isArray(body.files) || body.files.length === 0) {
    return c.json({ error: "No files provided" }, 400);
  }

  const sandboxFiles: Record<string, { content: string }> = {};
  for (const f of body.files) {
    const filename = f.name === "app.js" ? "index.js" : f.name;
    sandboxFiles[filename] = { content: f.content };
  }

  // CodeSandbox needs an explicit package.json so the bundler picks the
  // vanilla template; otherwise it falls back to "create-react-app" which
  // breaks plain HTML/JS sandboxes.
  if (!sandboxFiles["package.json"]) {
    sandboxFiles["package.json"] = {
      content: JSON.stringify(
        {
          name: "forge-export",
          version: "1.0.0",
          description: "Generated by FORGE",
          main: "index.js",
          scripts: { start: "parcel index.html --open", build: "parcel build index.html" },
          devDependencies: { "parcel-bundler": "^1.6.1" },
        },
        null,
        2
      ),
    };
  }

  try {
    const res = await fetch(
      "https://codesandbox.io/api/v1/sandboxes/define?json=1",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ files: sandboxFiles }),
      }
    );

    if (!res.ok) {
      const text = await res.text();
      return c.json(
        { error: `CodeSandbox ${res.status}: ${text.slice(0, 200)}` },
        502
      );
    }

    const data = (await res.json()) as CodeSandboxDefineResponse;
    if (!data.sandbox_id) {
      return c.json({ error: "CodeSandbox returned no sandbox_id" }, 502);
    }

    return c.json({
      sandbox_id: data.sandbox_id,
      url: `https://codesandbox.io/s/${data.sandbox_id}`,
    });
  } catch (err) {
    return c.json(
      { error: err instanceof Error ? err.message : "Unknown error" },
      502
    );
  }
});
